[project]
name = "voronoi-extraction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "open3d>=0.19.0",
    "torch>=2.7.1",
    "tqdm>=4.67.1",
    "trimesh>=4.6.13",
]
